# Generated by Django 3.0.1 on 2020-08-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=600)),
                ('correct_ans', models.CharField(max_length=600)),
                ('option_a', models.CharField(max_length=600)),
                ('option_b', models.CharField(max_length=600)),
                ('option_c', models.CharField(max_length=600)),
                ('option_d', models.CharField(max_length=600)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichoice.Story')),
            ],
        ),
    ]
