# Generated by Django 3.0.1 on 2020-08-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_title',
            field=models.CharField(default='Title Here', max_length=600),
        ),
    ]
