# Generated by Django 3.0.1 on 2020-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0002_story_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default='default correct answer', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='default', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='default', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='default', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='default', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='default question', max_length=600),
        ),
    ]
